# Generated by Django 5.2.1 on 2025-05-26 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0004_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='title',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='description',
            new_name='department',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='credits',
            new_name='stream',
        ),
    ]
