# Generated by Django 5.2.1 on 2025-05-26 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0005_rename_title_course_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='stream',
            field=models.CharField(max_length=20),
        ),
    ]
