# Generated by Django 5.2.1 on 2025-05-26 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0006_alter_course_stream'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.AlterField(
            model_name='biodata',
            name='department',
            field=models.TextField(max_length=20),
        ),
    ]
